### ISSUE TITLE
UUPDump script not working

### ISSUE THREAD

**Issue by ukhal** [thebookisclosed/AmperageKit#7]
I tried to create the ISO using the script on Friday, but unfortunately it was taking too long and I had to travel so I cancelled it, now when I try again I'm met with the following message:

Unable to retrieve data from Windows Update servers. Reason: EMPTY_FILELIST
If this problem persists, most likely the set you are attempting to download was removed from Windows Update servers.

Is there an alternate way to get the required ISO to test Recall?

**Comment by 0n1cOn3** [comment]
The ISO has been revoked at Microsoft due to the Recall disaster.

But a german forum got the ISO in de/en. You may use a translator if you cant read it

[deskmodder.de/blog/2024/04/27/windows-11-24h2-26100-iso-esd-deutsch-english](https://www.deskmodder.de/blog/2024/04/27/windows-11-24h2-26100-iso-esd-deutsch-english/)
