### ISSUE TITLE
Doesnt work on os build 26120.961

### ISSUE THREAD

**Issue by Max-109** [thebookisclosed/AmperageKit#9]
yo is this build not supported?

**Comment by thebookisclosed** [comment]
No. If the tool says your build doesn't have Recall then it doesn't have Recall. Microsoft removed it after the backlash.

**Comment by Max-109** [comment]
is it possible to install (without reinstalling whole windows) the required version?

**Comment by thebookisclosed** [comment]
If component cleanup didn't run yet you might be able to uninstall the latest CU in Settings, and then install an older MSU from places like UUPDump
![image](https://github.com/thebookisclosed/AmperageKit/assets/13197516/2d81c084-3a0c-4832-a616-9be7086b1f55)

**Comment by Max-109** [comment]
i just installed 26120.770 but it still says its not compatible

**Comment by thebookisclosed** [comment]
That doesn't make any sense, please send a screenshot of winver, the Amperage error, and the AppxManifest.xml from C:\Windows\SystemApps\MicrosoftWindows.Client.AIX_cw5n1h2txyewy

**Comment by Max-109** [comment]
https://imgur.com/a/3z1xpKl - ss
https://pastebin.com/QiQEGXQd - appxmanifest.xml

**Comment by thebookisclosed** [comment]
Just like the error says, you're trying to run an app that `is for a machine type other than the current machine.`
I was wondering what's going on because Amperage contains no errors about "compatibility." What you're seeing is errors built into Windows when you try to launch an app not built for your PC's architecture.

The second sentence of the readme says:
`At the moment, Amperage can only enable recall if your machine has an Arm64 CPU / SoC. That is, any Qualcomm Snapdragon, Microsoft SQ, or Ampere chipset.`

You're not using any of those. You're on a standard Intel/AMD PC which is *not* supported.
